name: Publish Web Page
on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo the environment
        run: |
          uname -a
          whoami
          date
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -a
