name: Publish Web Page
on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo the environment
        run: |
          uname -a
          whoami
          date
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -a
      - name: create ssh key file
        run: | 
          echo "$SSH_SECRET_KEY"  > key && chmod 600 key
          mkdir -m 700 .ssh 
          echo "$SSH_KNOWN_HOSTS" > .ssh/known_hosts && chmod 600 
        env:
          SSH_SECRET_KEY: ${{ secrets.SSH2 }}
          SSH_KNOWN_HOSTS: ${{ secrets.KNOWN_HOST }}
      - name: publish web page
        run: 
          scp -i key -r -P $PORT public/* $USERNAME@$HOST:~
